
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameDataTable.audio
{ 
    public enum Group
    {
        /// <summary>
        /// 背景音乐
        /// </summary>
        Bgm = 1,
        /// <summary>
        /// 音效
        /// </summary>
        Sound = 2,
        /// <summary>
        /// UI音效
        /// </summary>
        UISound = 3,
    }

} 

