
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameDataTable.ui
{ 
    public enum Group
    {
        /// <summary>
        /// 背景
        /// </summary>
        Background = 1,
        /// <summary>
        /// 普通
        /// </summary>
        Normal = 2,
        /// <summary>
        /// 弹窗提示
        /// </summary>
        PopTip = 3,
        /// <summary>
        /// 引导
        /// </summary>
        Guide = 4,
        /// <summary>
        /// 顶
        /// </summary>
        Top = 5,
        /// <summary>
        /// 特效
        /// </summary>
        Effect = 6,
        /// <summary>
        /// Debug
        /// </summary>
        Debug = 7,
    }

} 

