
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace GameConfig
{
    public partial class Tables
    {
        #region The Tables

        private item.TbItem m_TbItem;
        public item.TbItem TbItem 
        {
            get
            {
                if (m_TbItem == null)
                {
                    m_TbItem = new item.TbItem(m_DefaultLoader("item_tbitem"));
                    m_TbItem.ResolveRef(this);
                }
                return m_TbItem;
            }
            set
            {
                m_TbItem = value;
                m_TbItem.ResolveRef(this);
            }
        }

        #endregion

        public Tables(System.Func<string, ByteBuf> loader)
        {
        }

        private System.Func<string, JSONNode> m_DefaultLoader;

        public Tables(System.Func<string, JSONNode> loader)
        {
            SetDefaultLoader(loader);
            Init();
        }
        
        public void SetDefaultLoader(System.Func<string, JSONNode> loader)
        {
            m_DefaultLoader = null;
            m_DefaultLoader = loader;
        }

        //public partial void Init();

        public void Init(){}
    }
}
