
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace GameDataTable
{
public sealed partial class Sound : Luban.BeanBase
{
    public Sound(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["asset_name"].IsString) { throw new SerializationException(); }  AssetName = _buf["asset_name"]; }
        { if(!_buf["group_name"].IsNumber) { throw new SerializationException(); }  GroupName = (audio.Group)_buf["group_name"].AsInt; }
        { if(!_buf["priority"].IsNumber) { throw new SerializationException(); }  Priority = _buf["priority"]; }
        { if(!_buf["loop"].IsBoolean) { throw new SerializationException(); }  Loop = _buf["loop"]; }
        { if(!_buf["volume"].IsNumber) { throw new SerializationException(); }  Volume = _buf["volume"]; }
        { if(!_buf["spatial_blend"].IsNumber) { throw new SerializationException(); }  SpatialBlend = _buf["spatial_blend"]; }
        { if(!_buf["max_distance"].IsNumber) { throw new SerializationException(); }  MaxDistance = _buf["max_distance"]; }
    }

    public static Sound DeserializeSound(JSONNode _buf)
    {
        return new Sound(_buf);
    }

    /// <summary>
    /// 声音编号
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 资源名称
    /// </summary>
    public readonly string AssetName;
    /// <summary>
    /// 声音组名称
    /// </summary>
    public readonly audio.Group GroupName;
    /// <summary>
    /// 优先级
    /// </summary>
    public readonly int Priority;
    /// <summary>
    /// 是否循环
    /// </summary>
    public readonly bool Loop;
    /// <summary>
    /// 音量（0-1）
    /// </summary>
    public readonly float Volume;
    /// <summary>
    /// 声音空间混合量
    /// </summary>
    public readonly float SpatialBlend;
    /// <summary>
    /// 声音最大距离
    /// </summary>
    public readonly float MaxDistance;
   
    public const int __ID__ = 80074991;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "assetName:" + AssetName + ","
        + "groupName:" + GroupName + ","
        + "priority:" + Priority + ","
        + "loop:" + Loop + ","
        + "volume:" + Volume + ","
        + "spatialBlend:" + SpatialBlend + ","
        + "maxDistance:" + MaxDistance + ","
        + "}";
    }
}

}

