
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace GameDataTable
{
    public partial class Tables
    {
        #region The Tables

        private TbSound m_TbSound;
        public TbSound TbSound 
        {
            get
            {
                if (m_TbSound == null)
                {
                    m_TbSound = new TbSound(m_DefaultLoader("tbsound"));
                    m_TbSound.ResolveRef(this);
                }
                return m_TbSound;
            }
            set
            {
                m_TbSound = value;
                m_TbSound.ResolveRef(this);
            }
        }
        private TbUIForm m_TbUIForm;
        public TbUIForm TbUIForm 
        {
            get
            {
                if (m_TbUIForm == null)
                {
                    m_TbUIForm = new TbUIForm(m_DefaultLoader("tbuiform"));
                    m_TbUIForm.ResolveRef(this);
                }
                return m_TbUIForm;
            }
            set
            {
                m_TbUIForm = value;
                m_TbUIForm.ResolveRef(this);
            }
        }

        #endregion

        public Tables(System.Func<string, ByteBuf> loader)
        {
        }

        private System.Func<string, JSONNode> m_DefaultLoader;

        public Tables(System.Func<string, JSONNode> loader)
        {
            SetDefaultLoader(loader);
            Init();
        }
        
        public void SetDefaultLoader(System.Func<string, JSONNode> loader)
        {
            m_DefaultLoader = null;
            m_DefaultLoader = loader;
        }

        //public partial void Init();

        public void Init(){}
    }
}
