
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace GameDataTable
{
public sealed partial class UIForm : Luban.BeanBase
{
    public UIForm(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["asset_name"].IsString) { throw new SerializationException(); }  AssetName = _buf["asset_name"]; }
        { if(!_buf["group_name"].IsNumber) { throw new SerializationException(); }  GroupName = (ui.Group)_buf["group_name"].AsInt; }
        { if(!_buf["allow_multi_instance"].IsBoolean) { throw new SerializationException(); }  AllowMultiInstance = _buf["allow_multi_instance"]; }
        { if(!_buf["pause_covered_form"].IsBoolean) { throw new SerializationException(); }  PauseCoveredForm = _buf["pause_covered_form"]; }
    }

    public static UIForm DeserializeUIForm(JSONNode _buf)
    {
        return new UIForm(_buf);
    }

    /// <summary>
    /// 界面编号
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 资源名称
    /// </summary>
    public readonly string AssetName;
    /// <summary>
    /// 界面组名称
    /// </summary>
    public readonly ui.Group GroupName;
    /// <summary>
    /// 是否允许多个界面实例
    /// </summary>
    public readonly bool AllowMultiInstance;
    /// <summary>
    /// 是否暂停被其覆盖的界面
    /// </summary>
    public readonly bool PauseCoveredForm;
   
    public const int __ID__ = -1791876744;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "assetName:" + AssetName + ","
        + "groupName:" + GroupName + ","
        + "allowMultiInstance:" + AllowMultiInstance + ","
        + "pauseCoveredForm:" + PauseCoveredForm + ","
        + "}";
    }
}

}

