
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace GameDataTable
{
public sealed partial class vector2 : Luban.BeanBase
{
    public vector2(JSONNode _buf) 
    {
        { if(!_buf["x"].IsNumber) { throw new SerializationException(); }  X = _buf["x"]; }
        { if(!_buf["y"].IsNumber) { throw new SerializationException(); }  Y = _buf["y"]; }
    }

    public static vector2 Deserializevector2(JSONNode _buf)
    {
        return new vector2(_buf);
    }

    /// <summary>
    /// x
    /// </summary>
    public readonly float X;
    /// <summary>
    /// y
    /// </summary>
    public readonly float Y;
   
    public const int __ID__ = 337790799;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "x:" + X + ","
        + "y:" + Y + ","
        + "}";
    }
}

}

